######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 3 21:20:05 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
